VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "centos7" 
    config.vm.synced_folder '.', '/vagrant', disabled: true 
    config.vm.provision :ansible do |ansible|
        ansible.playbook = 'playbook.yml'
        ansible.extra_vars = { ansible_ssh_user: 'vagrant', vagrant: true }
        ansible.verbose = 'vv'
    end
end
